### ISSUE TITLE
Non-client code included into bundle: `__dirname` is not defined

### ISSUE THREAD

**Issue by kpyszkowski** [nextui-org/tailwind-variants#218]
**Describe the bug**
There is an error in the console saying the `__dirname` variable is not defined. The code that uses `__dirname` variable is included both in development and production build and only when the Tailwind config is wrapped with `withTV` transformer.

**To reproduce**

1. Wrap Tailwind config with `withTV` transformer
2. Start the application and open browser console
3. See error

**Expected behavior**
The code is not included into client bundle.

**Screenshots**
<img width="775" alt="image" src="https://github.com/user-attachments/assets/2a631866-cc6f-47f0-a292-3f8c624e65ce">

**Desktop**

- OS: macOS Sonoma 14.1
- Browser: Google Chrome
- Version: 129.0.6668.89

**Additional context**
NextJS 14.2.14

**Comment by craigrileyuk** [comment]
Same issue, same circumstances, when using the `withTV` transformer.

**Comment by qodeboy** [comment]
Same in latest Nuxt version. Transpile options doesn't help for some reason.

```
 ERROR  [uncaughtException] __dirname is not defined                                                          9:31:11 AM

    at t (node_modules/tailwind-variants/dist/chunk-FUBUDMV2.js:4:34)
    at node_modules/tailwind-variants/dist/chunk-FUBUDMV2.js:5:71
    at node:internal/process/task_queues:151:7
    at AsyncResource.runInAsyncScope (node:async_hooks:211:14)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:148:8)
```
